on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN_GITHUB: ${{ secrets.NPM_TOKEN_GITHUB }}

jobs:
  build:
    name: Build and publish npm package for GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
          scope: "@frontendweekly"
      - run: npm install
      - run: npm publish
