on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@frontendweekly"
      - run: npm install
        env:
          NPM_TOKEN_GITHUB: ${{ secrets.NPM_TOKEN_GITHUB }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.NPM_TOKEN_GITHUB }}
