

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com/frontendweekly
          token: ${{secrets.GITHUB_TOKEN}}
